services:
  - type: web
    name: astroapp-backend
    env: python
    plan: free
    buildCommand: |
      python --version
      pip --version
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PYTHONPATH
        value: .
      - key: ASTRO_CONFIG
        value: config/defaults.yaml
      - key: ASTRO_CALIBRATORS
        value: config/calibrators.json
      - key: ASTRO_HC_THRESHOLDS
        value: config/hc_thresholds.json
