services:
  - type: web
    name: astroapp-backend
    env: python
    plan: free
    branch: released
    buildCommand: |
      set -e
      python --version
      pip --version
      pip install --upgrade pip setuptools wheel
      # Prefer binary wheels for speed & reliability
      pip install --prefer-binary "numpy==1.26.4" "pyerfa>=2.0.1"
      # Project dependencies
      pip install --prefer-binary -r requirements.txt
      # ---- run tests remotely on Render when enabled ----
      if [ "${RUN_TESTS:-0}" = "1" ]; then
        pip install pytest hypothesis tzdata
        # Use the CI hypothesis profile (set below) and keep scope tight for speed
        pytest -q tests/test_timescales.py
      fi
      # ---------------------------------------------------
    startCommand: >
      gunicorn app.main:app
      --bind 0.0.0.0:$PORT
      --worker-class gthread
      --workers=2
      --threads=4
      --timeout=120
      --graceful-timeout=30
      --max-requests=500
      --max-requests-jitter=50
      --worker-tmp-dir /dev/shm
      --access-logfile -
      --error-logfile -
      --log-level info
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      # Toggle remote test gate during build (1=run tests, 0=skip)
      - key: RUN_TESTS
        value: "1"
      # Ensure deterministic tests & CI settings
      - key: HYPOTHESIS_PROFILE
        value: ci
      - key: TZ
        value: UTC

      - key: FLASK_ENV
        value: production
      - key: NETLIFY_ORIGIN
        value: "*"
      - key: ASTRO_CONFIG
        value: config/defaults.yaml
      - key: ASTRO_CALIBRATORS
        value: config/calibrators.json
      - key: ASTRO_HC_THRESHOLDS
        value: config/hc_thresholds.json
      - key: ASTRO_LEAP_POLICY
        value: warn
      - key: ASTRO_DUT1_BROADCAST
        value: "0"
      - key: ASTRO_DEBUG_VERBOSE
        value: "0"

      # (optional) make logs flush immediately
      - key: PYTHONUNBUFFERED
        value: "1"
      # (optional) reduce disk writes & pip cache size
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
