services:
  - type: web
    name: astroapp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --preload --workers=2 --threads=4 --timeout=120
    healthCheckPath: /api/health-check   # use the route you already expose
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: Asia/Kolkata
      - key: NETLIFY_ORIGIN
        value: "*"   # we'll lock to Netlify later

      # existing config files you already reference
      - key: ASTRO_CONFIG
        value: config/defaults.yaml
      - key: ASTRO_CALIBRATORS
        value: config/calibrators.json
      - key: ASTRO_HC_THRESHOLDS
        value: config/hc_thresholds.json
